# Generated by Django 3.1.1 on 2020-09-25 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=30)),
                ('user_nm', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=100)),
                ('user_pwd', models.CharField(max_length=128)),
                ('user_telno', models.CharField(default=None, max_length=12, null=True)),
                ('user_birthday', models.CharField(max_length=8)),
                ('user_auth_yn', models.CharField(default='N', max_length=1)),
                ('user_acc_pub_yn', models.CharField(default='Y', max_length=1)),
                ('user_prof_pic', models.CharField(max_length=500)),
                ('user_prof_bio', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_sno', models.IntegerField()),
                ('tw_psno', models.IntegerField()),
                ('tw_content', models.CharField(max_length=500)),
                ('tw_image_url', models.CharField(default=None, max_length=500, null=True)),
                ('tw_gif_url', models.CharField(default=None, max_length=500, null=True)),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwTweet_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwFollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('follower_user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user_id', to=settings.AUTH_USER_MODEL)),
                ('following_user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwFollowUser_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TwAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_act_sno', models.IntegerField()),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('like_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qt_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qt_user_id', to=settings.AUTH_USER_MODEL)),
                ('rt_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_user_id', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwAct_user_id', to='twitterCloneApp.twtweet')),
            ],
        ),
    ]
