# Generated by Django 3.1.1 on 2020-09-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='아이디를 입력해주세요. ', max_length=30)),
                ('user_nm', models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='이름을 입력해주세요. ', max_length=45)),
                ('user_email', models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='이메일 주소를 입력해주세요. ', max_length=100)),
                ('user_telno', models.CharField(default=None, max_length=12, null=True)),
                ('user_birthday', models.CharField(max_length=8)),
                ('user_pwd', models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='비밀번호를 입력해주세요. ', max_length=128)),
                ('user_auth_yn', models.CharField(default='N', max_length=1)),
                ('user_acc_pub_yn', models.CharField(default='Y', max_length=1)),
                ('user_prof_pic', models.CharField(max_length=500)),
                ('user_prof_bio', models.CharField(max_length=500)),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_sno', models.IntegerField()),
                ('tw_psno', models.IntegerField()),
                ('tw_content', models.CharField(max_length=500)),
                ('tw_image_url', models.CharField(default=None, max_length=500, null=True)),
                ('tw_gif_url', models.CharField(default=None, max_length=500, null=True)),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwTweet_user_id', to='twitterCloneApp.twuser')),
            ],
        ),
        migrations.CreateModel(
            name='TwFollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('follower_user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_user_id', to='twitterCloneApp.twuser')),
                ('following_user_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_user_id', to='twitterCloneApp.twuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwFollowUser_user_id', to='twitterCloneApp.twuser')),
            ],
        ),
        migrations.CreateModel(
            name='TwAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tw_act_sno', models.IntegerField()),
                ('data_del_yn', models.CharField(default='N', max_length=1)),
                ('frt_user_id', models.CharField(max_length=30)),
                ('frt_reg_date', models.DateTimeField(auto_now_add=True)),
                ('last_user_id', models.CharField(max_length=30)),
                ('last_chg_date', models.DateTimeField(auto_now=True)),
                ('like_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterCloneApp.twuser')),
                ('qt_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qt_user_id', to='twitterCloneApp.twuser')),
                ('rt_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt_user_id', to='twitterCloneApp.twuser')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwAct_user_id', to='twitterCloneApp.twtweet')),
            ],
        ),
    ]
