# Generated by Django 3.1.1 on 2020-09-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twuser',
            name='user_email',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text={'user_email': '이메일 주소를 입력해주세요. ', 'user_id': '아이디를 입력해주세요. ', 'user_nm': '이름을 입력해주세요. ', 'user_pwd': '비밀번호를 입력해주세요. '}, max_length=100),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_id',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text={'user_email': '이메일 주소를 입력해주세요. ', 'user_id': '아이디를 입력해주세요. ', 'user_nm': '이름을 입력해주세요. ', 'user_pwd': '비밀번호를 입력해주세요. '}, max_length=30),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_nm',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text={'user_email': '이메일 주소를 입력해주세요. ', 'user_id': '아이디를 입력해주세요. ', 'user_nm': '이름을 입력해주세요. ', 'user_pwd': '비밀번호를 입력해주세요. '}, max_length=45),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_telno',
            field=models.CharField(default=None, help_text={'user_email': '이메일 주소를 입력해주세요. ', 'user_id': '아이디를 입력해주세요. ', 'user_nm': '이름을 입력해주세요. ', 'user_pwd': '비밀번호를 입력해주세요. '}, max_length=12, null=True),
        ),
    ]
