# Generated by Django 3.1.1 on 2020-09-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0002_auto_20200920_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twact',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwAct_user_id', to='twitterCloneApp.twtweet'),
        ),
        migrations.AlterField(
            model_name='twfollowuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwFollowUser_user_id', to='twitterCloneApp.twuser'),
        ),
        migrations.AlterField(
            model_name='twtweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwTweet_user_id', to='twitterCloneApp.twuser'),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_email',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='이메일 주소를 입력해주세요. ', max_length=100),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_id',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='아이디를 입력해주세요. ', max_length=30),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_nm',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='이름을 입력해주세요. ', max_length=45),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_pwd',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='비밀번호를 입력해주세요. ', max_length=128),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_telno',
            field=models.CharField(default=None, max_length=12, null=True),
        ),
    ]
