# Generated by Django 3.1.1 on 2020-09-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0002_remove_twuser_user_auth_yn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twtweet',
            name='tw_sno',
        ),
    ]
