# Generated by Django 3.1.1 on 2020-09-21 03:00

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0003_auto_20200920_2309'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='twuser',
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='twuser',
            old_name='user_pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='twuser',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AddField(
            model_name='twuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
