# Generated by Django 3.1.1 on 2020-10-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0005_auto_20201004_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twtweet',
            name='tw_gif_url',
        ),
        migrations.AlterField(
            model_name='twtweet',
            name='tw_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
