# Generated by Django 3.1.1 on 2020-09-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0005_auto_20200921_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twuser',
            name='user_pwd',
            field=models.CharField(error_messages={'user_email': '이메일 형식이 잘못되었습니다. ', 'user_id': '아이디는 최대 30자로 설정 가능합니다. ', 'user_nm': '이름은 최대 15자로 설정 가능합니다.  ', 'user_pwd': '비밀번호는 6자 이상 12자 이하, 영문+숫자 조합이어야 합니다.'}, help_text='비밀번호를 입력해주세요. ', max_length=128),
        ),
    ]
