# Generated by Django 3.1.1 on 2020-10-12 13:06

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0009_auto_20201011_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twtweet',
            name='tw_image_url',
        ),
        migrations.CreateModel(
            name='TwImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='img/')),
                ('twTweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitterCloneApp.twtweet')),
            ],
        ),
    ]
