# Generated by Django 3.1.1 on 2020-11-01 13:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0011_auto_20201101_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twuser',
            name='user_prof_bio',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='user/'),
        ),
    ]
