# Generated by Django 3.1.1 on 2020-11-08 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('twitterCloneApp', '0012_auto_20201101_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twact',
            old_name='user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='twfollowuser',
            old_name='last_chg_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='twfollowuser',
            old_name='user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='twtweet',
            old_name='last_chg_date',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='twuser',
            old_name='last_chg_date',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='twact',
            name='last_chg_date',
        ),
        migrations.AddField(
            model_name='twfollowuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twtweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='twimages',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_sno', to='twitterCloneApp.twtweet'),
        ),
        migrations.AlterField(
            model_name='twtweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweet_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_acc_pub_yn',
            field=models.CharField(choices=[('0', 'Y'), ('1', 'N')], max_length=1),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='twuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
