# Generated by Django 3.1.1 on 2020-11-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0013_auto_20201108_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twtweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TwUser_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
