# Generated by Django 3.1.1 on 2020-11-08 14:39

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0014_auto_20201108_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='twtweet',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
