# Generated by Django 3.1.1 on 2020-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterCloneApp', '0015_twtweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='twtweet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
